service: serverless-task

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.serverlessTableName}

plugins:
  - serverless-iam-roles-per-function

custom:
  serverlessTableName: serveless-task-${self:provider.stage}

functions:
  getBlogs:
    handler: src/api.getBlog
    name: get-blog
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: blogs/{id}
          method: GET
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:GetItem"
        Resource: !GetAtt ServerlessTable.Arn
  createBlog:
    handler: src/api.createBlog
    name: create-blog
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: blogs
          method: POST
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:PutItem"
        Resource: !GetAtt ServerlessTable.Arn
  updateBlog:
    handler: src/api.updateBlog
    name: update-blog
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: blogs/{id}
          method: PUT
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:UpdateItem"
        Resource: !GetAtt ServerlessTable.Arn
  deleteblogPost:
    handler: src/api.deleteBlog
    name: delete-blog
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: blogs/{id}
          method: DELETE
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:DeleteItem"
        Resource: !GetAtt ServerlessTable.Arn
  getAllPosts:
    handler: src/api.getAllBlogs
    name: get-all-blogs
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: blog
          method: GET
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:Scan"
        Resource: !GetAtt ServerlessTable.Arn

resources:
  Resources:
    ServerlessTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.serverlessTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1